name: ginkgo_app
description: 银杏应用 - 面向老年人的智能手机教学应用

# 发布版本号
version: 0.1.0+1

environment:
  sdk: ">=3.0.0 <4.0.0"

dependencies:
  flutter:
    sdk: flutter
  cupertino_icons: ^1.0.5
  # 状态管理
  provider: ^6.0.5
  # 路由管理
  go_router: ^10.1.2
  # 本地存储
  shared_preferences: ^2.2.0
  # 网络请求
  http: ^1.1.0
  dio: ^5.3.2
  # 图片处理
  cached_network_image: ^3.2.3
  # 视频播放
  video_player: ^2.7.0
  # 社交分享
  share_plus: ^7.1.0
  # 图标
  font_awesome_flutter: ^10.5.0
  # 表单验证
  form_field_validator: ^1.1.0
  # 本地化
  flutter_localizations:
    sdk: flutter
  intl: ^0.19.0
  # 社交界面相关依赖
  line_icons: ^2.0.1
  google_fonts: ^4.0.1
  animations: ^2.0.7
  
  # 其他已有的依赖...
dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^2.0.2
  mockito: ^5.4.2
  build_runner: ^2.4.6

flutter:
  uses-material-design: true
  
  assets:
    - assets/images/
    - assets/icons/
    - assets/videos/
  
  # 暂时注释掉字体配置，因为字体文件不存在
  # fonts:
  #   - family: GinkgoFont
  #     fonts:
  #       - asset: assets/fonts/GinkgoFont-Regular.ttf
  #       - asset: assets/fonts/GinkgoFont-Bold.ttf
  #         weight: 700